name: Lint python file

on:
  # PR中にPushしたときに発火
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  flake3:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
      - name: Checkout
        uses: actions/checkout@v3
      - name: flake3
        uses: matias-martini/flake8-pr-comments-action@main
        with:
          github_token: ${{ github.token }}

