name: PR Template

on:
  pull_request:
    types:
      - opened

jobs:
  pr_template:
    runs-on: ubuntu-latest

    steps:
      - name: Set PR template
        run: |
          template=".github/PULL_REQUEST_TEMPLATE.md"
          pr_title="${{ github.event.pull_request.title }}"
          pr_source="${{ github.event.pull_request.head.ref }}"
          pr_target="${{ github.event.pull_request.base.ref }}"
          current_date="$(date +'%Y-%m-%d %H:%M:%S')"

          sed -e "s/{{CURRENT_DATE}}/${current_date}/" -e "s/{{PR_SOURCE}}/${pr_source}/" -e "s/{{PR_TARGET}}/${pr_target}/" "$template" > pr_template.md
          mv pr_template.md "$template"
